### ISSUE TITLE
Scss files containing $alert-padding incompatible with new bootstrap alpha 5

### ISSUE THREAD

**Issue by cornillemichiel** [telerik/kendo-theme-bootstrap#49] opened 2016-11-09 15:29 UTC
Changelog for new alpha release:

https://github.com/twbs/bootstrap/issues/20630
files affected: node_modules/@telerik/kendo-theme-bootstrap/src/notification/_layout.scss

Use **$alert-padding-x** and **$alert-padding-y** instead.

**Update:** It seems none of the alpha5 changes have been factored in yet, a handy list can be found here: 
http://blog.getbootstrap.com/2016/10/19/bootstrap-4-alpha-5/

**Comment by joneff** [comment] 2016-11-15 13:24
The issue is already fixed in the v2 branch, will be the base for the official release: 5ce60855c20cb943bd9ede0ddcb0a762d31a4144

**Closed by joneff** 2016-11-15 13:24 UTC
