### ISSUE TITLE
ListView issue.

### ISSUE THREAD

**Issue by simonssspirit** [telerik/kendo-theme-bootstrap#230] opened 2017-04-27 10:22 UTC
- [x] **The text of the h3 element is clipped for some of the items.**
Please refer to the screenshot:

![image](https://cloud.githubusercontent.com/assets/11087921/25479151/8554e83c-2b4c-11e7-979e-f2dd0e51f3aa.png)

**Comment by joneff** [comment] 2017-08-23 15:04
The issue is due to bootstrap having slightly bigger font-size and line-height then the rest of the themes. It's a demo issue

**Comment by joneff** [comment] 2017-08-23 15:09
Fixed by https://github.com/telerik/kendo/commit/9cdeca3ef4612cda859045389b6852553e6826da

**Closed** 2017-08-24 07:28 UTC
Labels: Invalid
